### ISSUE TITLE
Action use

### ISSUE THREAD

**Issue by jstvnsn** [0xC0000054/gmic-8bf#11]

**Comment by jstvnsn** [comment]
This is not an issue directly ... but, I found today that the plug-in works within a standard Photoshop Action. Was this an intentional design step which you took? It is not mentioned in the documentation.

**Comment by jstvnsn** [comment]
This is not an issue directly ... but, I found today that the plug-in works within a standard Photoshop Action. Was this an intentional design step? (It is not mentioned in the documentation.)

**Comment by 0xC0000054** [comment]
I have not done anything to support Photoshop Actions, Photoshop probably has a compatibility mode that allows any plug-in to be used with Actions.

**Comment by jstvnsn** [comment]
If so, that's new. I know that it was not the case some years back. It's a bonus for me!

**Comment by 0xC0000054** [comment]
> If so, that's new. I know that it was not the case some years back. It's a bonus for me!

I reread some of the Photoshop SDK documentation on Actions, and it appears that this feature was present from when Actions were introduced in Photoshop 4.0.
This makes sense, the Actions feature would not have been as useful if it was incompatible with a user's existing plug-ins.

I did not add Actions support to the documentation because this plug-in has a few compatibility issues with it:
* G'MIC effects that produce multiple images or resize the image save the results to an external file, which is not friendly to an Actions / batch processing workflow.
* The G'MIC-Qt ability to "layer" multiple effects in a single session, this is also not friendly to an Actions / batch processing workflow.
* G'MIC-Qt only remembers the most recently used filter.
* The Actions "Never show UI" setting is ignored:
  * G'MIC-Qt handles its own UI.
  * The plug-in does its own error handling to support other (broken) hosts.

There may also be other compatibility issues that I have missed.

**Comment by jstvnsn** [comment]
There are many commercially-offered plug-ins which cannot be incorporated into Actions. To the point, that those who do have this capability are very explicit about it. For example, see here: https://jixipix.com/watercolor-studio/details.html (in the section titled PHOTOSHOP PLUGIN). Concerning "the G'MIC-Qt ability to "layer" multiple effects in a single session": I will take a look at that (since that is of most interest to me).

**Comment by 0xC0000054** [comment]
> Concerning "the G'MIC-Qt ability to "layer" multiple effects in a single session": I will take a look at that (since that is of most interest to me).

That is documented in the Usage section of the plug-in read-me:

> You can "layer" multiple G'MIC effects in a single session by clicking the Apply button. Note that only the most recently applied effect will be used when the plug-in is invoked through the "Last Filter" or "Repeat Filter" commands.

I already mentioned the most recently used effect limitation in my previous post.

> Where is the "Never show UI" setting to be found?

In the Actions panel to the right of the enable/disable check mark.
Adobe's [About actions and the Actions panel](https://helpx.adobe.com/photoshop/using/actions-actions-panel.html#actions_panel_overview) page has an image that shows its location, search for "Modal" on that page.
That option instructs a plugin that it should not show a dialog, if possible.

**Comment by 0xC0000054** [comment]
I improved the integration with Actions for the next version.
The plugin will now show the name of the G'MIC effect and the Input Mode in the actions palette.

![Gmic-8bf-actions](https://user-images.githubusercontent.com/26996983/121541688-c329c680-c9c4-11eb-9aa0-ca3a12c6c603.png)
