### ISSUE TITLE
A file I/O error occured

### ISSUE THREAD

**Issue by DiegoRRR** [0xC0000054/gmic-8bf#13]
Hello

When I try to open G'MIC I now have this error message :
G'MIC-Qt filter
A file I/O error occured.

It used to work though.

I deleted the "GmicPlugin.8bf" file and the "gmic" folder, downloaded and copied them again in photoshop plugin folder, but I still have this message. I also tried to use an older version but it doesn't help neither.

Can you help please ?

Thanks

**Comment by 0xC0000054** [comment]
I am not able to reproduce that error, the plugin is working for me.

Unfortunately, that is one of the generic error codes the plugin can return, and it does not give any indication of where the problem is.

**Comment by 0xC0000054** [comment]
>  I deleted almost all layers, but two. If I delete either of these layers, it works, but as long as these are still there, it gives the error.

The issue was a bug in my layer reading code.
The top layer has a different size than the bottom layer, and I was assuming that all layers would match the image size.

Strangely, the bottom layer shows image data in G'MIC-Qt that is not visible in Photoshop. This behavior also occurs with the built-in Filter Gallery and Liquify filters, so I have no idea what is going on. 😕
