### ISSUE TITLE
Windows Defender finds virus

### ISSUE THREAD

**Issue by irvcobb** [0xC0000054/gmic-8bf#2]
![clipboard](https://user-images.githubusercontent.com/35406346/101266194-4286c680-3712-11eb-8bd5-8ea37cf0c679.png)
I'm seeing this whenever I try to install. Have DL'd previous versions and all give this when scanned. Oddly, this did not occur with v. 1.0, but when I moved up to 1.0.2. As mentioned, now it happens with any version. I really think this is a false positive, but it's worth checking, I think.

Edition	Windows 10 Home
Version	20H2
Installed on	‎6/‎10/‎2020
OS build	19042.662
Experience	Windows Feature Experience Pack 120.2212.551.0

**Comment by 0xC0000054** [comment]
I just submitted both the x86 and x64 builds of version 1.0.2 to VirusTotal.
Based on the scan results it looks like a false positive that may have been fixed in a recent signature update.

 GmicPlugin_x64.zip: https://www.virustotal.com/gui/file/e94bdfe0eceaf5fee2700f891c810af916fe86798466f7c428cb921bd4516353/detection

GmicPlugin_x86.zip: https://www.virustotal.com/gui/file/eff2747f2eef1a5daf54c64cf6ac91fe904e5db68e3e8ca6dd0ede3097d64e38/detection

**Comment by irvcobb** [comment]
Thanks for checking. I presumed a false positive, but thought it was worth reporting.
