### ISSUE TITLE
compatibility with Mac?

### ISSUE THREAD

**Issue by hebustetram** [0xC0000054/gmic-8bf#6]
First, congratulations for creating a plug-in that allows Photoshop users to discover the wonders of Gmic and FOSS applications.

Is the current plug-in meant to be compatible with MacOS?
When re-opening Photoshop it fails to load gmic in filters Filters.

I am on MacOS 10.15 Catalina
I have dropped the file GmicPlugin.8bf and gmic folder into the plug-in folder in Mac for the last two versions of Photoshop:
MainDrive/Applications/Adobe Photoshop 2021/Plug-ins
MainDrive/Applications/Adobe Photoshop 2020/Plug-ins

Photoshop does open all the other plug-ins stored in those folders. 
However all my other plug-ins are set as bundles _**.plugin**_
Inside the package the Info.plist  files do refer to <key>**CFBundlePackageType**</key> <string>**8BFM**</string>

**Comment by 0xC0000054** [comment]
> Is the current plug-in meant to be compatible with MacOS?

No, it is currently only available for Windows.

Both the plugin and G'MIC would have to be recompiled on macOS.
G'MIC does not currently offer a macOS build for any image editor.
I designed the plugin so that is should be possible to port it to macOS, but there is also a fairly large amount of OS-specific code that would have to be rewritten.

**Comment by hebustetram** [comment]
Thanks for the info.
